import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import { CartProvider } from "./context/CartContext";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Header/Navbar";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
